#apiVersion: extensions/v1beta1
apiVersion: v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /
  labels:
    #app: {{ .ServiceName }}
    app: advent
  #name: {{ .ServiceName }}
  name: advent
spec:
  backend:
    #serviceName: {{ .ServiceName }}
    serviceName: advent
    servicePort: 80
  rules:
    - host: advent.test
      http:
        paths:
          - path: /
            backend:
              #serviceName: {{ .ServiceName }}
              serviceName: advent
              servicePort: 80